# url: 'https://pins.crmplace.com/Api/access_token'
url: 'https://pinsims.crmplace.com/Api/access_token'
baseurl: 'https://pinsims.crmplace.com/Api'
api-version: 'V8'
key: '122386c2-1710-c290-438a-60dafef04729'
secret: '6df99f18-d0de-4853-8226-65d27d674ba2'
username: 'MiPINS'
password: 'goldfish-SAPPY-serene'
zendesk_token: 'C9yZPMVcE5UPPTiundacEJ0wHyNGsKJuELvP07tD'
zendesk_url: 'https://pinssupport.zendesk.com/api/v2'
zendesk_user: 'svc_zendesk@planninginspectorate.gov.uk'
zendesk_service_password: '9*scw21398AAkjas12!'
zendesk_service_email_password: '9*scw2]7w1\XmX54'